(source gnu)
(source melpa)
(source melpa-stable)

(depends-on "cask")
(depends-on "company")
(depends-on "tabbar")
(depends-on "yatex")
(depends-on "magit")
;; (depends-on "rainbow-delimiters" :git "https://github.com/Fanael/rainbow-delimiters.git")
;; (depends-on "highlight-indentation" :git "https://github.com/antonj/Highlight-Indentation-for-Emacs.git")
(depends-on "csharp-mode")
(depends-on "scala-mode")
(depends-on "php-mode")
(depends-on "js2-mode")
(depends-on "web-mode")
(depends-on "yaml-mode")
(depends-on "markdown-mode")
(depends-on "fish-mode")
(depends-on "smartparens")