(source gnu)
(source melpa)
(source melpa-stable)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

(depends-on "tramp")
(depends-on "company")
(depends-on "tabbar")
(depends-on "yatex")
(depends-on "rainbow-delimiters" :git "https://github.com/Fanael/rainbow-delimiters.git")
(depends-on "highlight-indentation" :git "https://github.com/antonj/Highlight-Indentation-for-Emacs.git")
(depends-on "csharp-mode")
(depends-on "scala-mode")
;; (depends-on "r-mode")
;; (depends-on "ess-site")
(depends-on "php-mode")
(depends-on "js2-mode")
(depends-on "yaml-mode")
(depends-on "fish-mode")
(depends-on "haml-mode")

